### ISSUE TITLE
7. Login Funcional

### ISSUE THREAD

**Issue by ghost** [ISWPOLI/Pacto-de-Honor#149]
- [x] Formulario  de Login  @Basespoli

- [x] Conexión a base de datos @juankrlos08 @Basespoli

- [x] Pruebas funcionales de base de datos @Basespoli

- [x] Captura de  datos en base de datos @juankrlos08  

- [x] Verificación de registro @juankrlos08 

- [x]  Acceso a Historia de Juego @BasesPoli

**Comment by ghost** [comment]
#23 #24 #27 #79 #45 #46 #4 Todos estos Issues están relacionados a esta misma épica, que esta en backLog y se esta desarrollando.  Todas se remplazan por 1.2.6 Sprint 10 de Marzo -Login Funcional #149.

**Comment by juankrlos08** [comment]
se presenta una muestra del login, con sus respectivos botones ademas se usa una base de datos que se conectara con la ya existente para adquirir todos los datos requeridos de los usuarios.

Este seria script que se hablo con los encargados de la base de datos para realización de la misma:

CREATE TABLE usuarios (
id_usuario int(10) NOT NULL,
Nombre varchar(100) NOT NULL,
Apellido varchar(100) NOT NULL,
email varchar(150) NOT NULL,
pais varchar(50) NOT NULL,
ciudad varchar(50) NOT NULL,
usuario varchar(50) NOT NULL,
password varchar(20) NOT NULL,
id_role int(10) NOT NULL,
fecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

**Comment by ghost** [comment]
`<!DOCTYPE html PUBLIC "http:localhost/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/Login.html">
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset="utf-8">
  <title>Login Pacto de Honor</title>
  
  
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="bootstrap/css/bootstrap-responsive.css">
  <script src="main.js"></script> 
  <link rel="stylesheet" href="main.css">
  </style>
</head>

<body>
  <img src="C:/xampp/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/spint/logo.png" .circle:hover>
  
  <div class="campos">
      <form action="validar.php" method="POST">
      <br>
      <input class="form-group" type="text" name="rusuario" placeholder="Email"/>
      <input type="password" name="rcontraseña" placeholder="Password"/>
      <p><a href="file:///C:/xampp/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/Forgot.html">Forgot Password</a></p>
      <p><a href="file:///C:/xampp/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/Registro.html">Registrarse</a>  </p>
      <input button href="#" id="Login" class="btn btn-primary" type="submit" value="Login"/>
      </p>
      </form>
        
      <br>
      
      <div class="btn-group">
      <button href="#" id="facebook" class=" fa fa-facebook" type="submit">Facebook</button>
      <button href="#" id="google" class="fa fa-google-plus" type="submit">Google</button>
      <button href="#" id="Microsoft" class="fa fa-microsoft" type="submit">Microsoft </button>
      
      </div>
      <div align="center">Derechos Reservados &copy; Copyright HackDemons 2010-2017 </div>
  </div>
 <?php
    if(isset($_POST['submit'])){
      require("registro.php");
    }
  ?>
<script>
  // Load the SDK asynchronously
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

</body>
</html>
`

**Comment by ghost** [comment]
<!DOCTYPE html PUBLIC "http:localhost/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/Login.html">
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset="utf-8">
  <title>OlvidoClave Pacto de Honor</title>
	  
	  
	  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">  
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	  <script src="main.js"></script> 
	  <link rel="stylesheet" href="main.css">
	  </style>
</head>

<body>
	 <img src="C:/xampp/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/spint/logo.png" .circle:hover>
	  
	  <p><a href="file:///C:/xampp/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/Registro.html">Recupera tu clave</a>  </p>
	 <div class="campos">
	      <form method="POST" action="validar.php">
	      <input type="password" name="rusuario" placeholder="Email de Registro"/>
	      </form>
	      <br>
	      <button href="#" id="Login" class="btn btn-primary" type="submit">Enviar</button>
	      <button href="#" id="Login" class="btn btn-primary" type="submit">Cancelar</button>
	      <div align="center">Derechos Reservados &copy; Copyright HackDemons 2010-2017 </div>
	 </div>
</body>
</html>

**Comment by ghost** [comment]
`<!DOCTYPE html PUBLIC "http:localhost/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/Login.html">
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset="utf-8">
  <title>Registro Pacto de Honor</title>
	  
	  
	  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	  <script src="main.js"></script> 
	  <link rel="stylesheet" href="main.css">
	  </style>
</head>

<body>
	 <img src="C:/xampp/htdocs/snippets_cades_login/Autentificacion_Pacto_Honor/spint/logo.png" .circle:hover>
	  
	<fieldset> 
	 <div class="form-group">
	    <form action="validar.php method="POST" ">
	    <input type="text" name="rnombres" placeholder="Nombre"/>
	    <input type="text" name="rusuario" placeholder="Email"/>
	    <input type="password" name="rcontraseña" placeholder="Password"/>
	    <input type="password" name="rrcontraseña" placeholder="Confirmar Password"/>
	 </div>
		<div class="form-group">
	    <br>
	    <button href="#" id="Login" class="btn btn-primary" type="submit">Registrate</button>	
	    </br>
	    
	      
	</fieldset>
	 	<div align="center">Derechos Reservados &copy; Copyright HackDemons 2010-2017 </div>
	 	</form>
	 	</div>

</body>
</html>`

**Comment by ghost** [comment]
Se crearon mokup para el login preliminar unificando todos los que se habían trabajado.

![login pacto-honor](https://cloud.githubusercontent.com/assets/25758763/23820229/52036010-05e2-11e7-91e9-d64826028180.png)

**Comment by ghost** [comment]
Se crearon mokup para el registro preliminar unificando todos los que se habían trabajado.

![registro pacto honor](https://cloud.githubusercontent.com/assets/25758763/23820234/77a3d8ea-05e2-11e7-93e2-a6b6e92dd77f.png)

**Comment by ghost** [comment]
Se crearon mokup para el Olvido Clave preliminar unificando todos los que se habían trabajado.

![forgotpassword](https://cloud.githubusercontent.com/assets/25758763/23820236/86e9db42-05e2-11e7-9218-c10aaafc53d7.png)

**Comment by ghost** [comment]
- [x]   Formulario de Login fueron cargados en Frontend como se indico.

https://github.com/ISWPOLI/Pacto-de-Honor/tree/master/FRONTEND/html

**Comment by ghost** [comment]
- [x] Conexión a base de datos @juankrlos08 @Basespoli

- [x] Pruebas funcionales de base de datos @Basespoli

- [x] Verificación de registro @juankrlos08 

fueron cargados en Frontend como se indico.
https://github.com/ISWPOLI/Pacto-de-Honor/tree/master/FRONTEND/js/login

**Comment by jolarter** [comment]
Les pido a todos a la hora de desarrollar que la comunicación sea fluida y compartan la información de lo que están haciendo para asegurarse que lo que harán si es compatible con lo de los demás.

LA AUTENTICACIÓN DEBERÁ SER REALIZADA CON JPA.

**Comment by ghost** [comment]
Se solicita que por favor se verifiquen las tareas asignadas propuestas en este issues  para validar que cumplan con todos los requerimientos  y sean correctas, ademas las reasignar de las tareas de juan a ivan ya que la persona que me va entrar a colaborar es ivan  barrantes  y  no estoy  trabajando solo en esta issues.

**Comment by CamilaG08** [comment]
Se asigna la característica #220 en la cual se realizan las especificaciones.

**Comment by ghost** [comment]
Una vez finalizado el registro de usuario para la autentificación de Usuario-Jugador pasaremos a implementar la autenticación mediante redes sociales teniendo en cuenta que esta sería la tarea principal junto con la Issues #220  donde se despliegan todo el resto.

**Comment by ghost** [comment]
Se sigue trabajando en el resto de tareas toda la semana  donde se contempla la integración y la autentificación con redes sociales, se contextualiza todo el trabajo el dia de hoy.

**Comment by ghost** [comment]
Se contempla que aunque se trabaja a diario en la semana una dedicación de tiempo, no se puede realizar comment o sustentar en la issues todo el trabajo puntual que se está realizando en ese mismo dia por el poco tiempo.

**Comment by DiegOliveros** [comment]
@Basespoli entiendo que no se refiere a comment si no a commit, sobre la rama que está trabajando se entiende que deben existir adiciones y modificaciones al código, relacionadas con una issue, que en últimas deberían ser un commit.

**Comment by ghost** [comment]
@DiegOliveros  Se entiende que las modificaciones de código se relacionan a la rama en la que estoy desplegando lo que indico es que no se se hacen en el mismo dia que se decodifica si no posterior o un día aleatorio en el que cuente con la disponibilidad de tiempo, gracias.

**Comment by CamilaG08** [comment]
Debido al cambio de asignaciones se mueve al último sprint

**Comment by CamilaG08** [comment]
Se crea la nueva característica con el Issue #601 para la re - estructuración del login
