### ISSUE TITLE
1.Base de Datos

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#178]
Creación de modelo relacional de base de datos, a partir de los requerimientos definidos por el proyecto

- [ ]  modelo entidad relación 
- [ ]  Scripts de base de datos
- [ ]  Generación de Data base de datos
