### ISSUE TITLE
1.4.5 Revisar todo lo necesario para la versión móvil

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#195]
**Descripción**
Revisar todo lo necesario para la versión móvil
**Tareas**
- [x] Averiguar y documentar que se necesita para la versión móvil.
- [x] Averiguar y documentar ¿Qué librerías se necesitan de Phaser?
- [ ] Implementar el joystick.

**Comment by KmiArthur** [comment]
# Documento para pasar HMTL5 a App Móvil
(tiempo trabajo: 4h)

Alternativas:
- Cordova
- Cocoon

[Phaser to Mobile.pdf](https://github.com/ISWPOLI/Pacto-de-Honor/files/843494/Phaser.to.Mobile.pdf)

### Guía Útil de [cordova-phaser](https://github.com/amex4152/cordova-phaser)
Install: `npm install cordova-phaser@1.0.3`

### Plantilla Joystick:
[VirtualJoystick.js.zip](https://github.com/ISWPOLI/Pacto-de-Honor/files/843496/VirtualJoystick.js.zip)

**Comment by CamilaG08** [comment]
Se requiere la finalización de las tareas para dar cierre al Sprint 5. ( @KmiArthur  )

**Comment by CamilaG08** [comment]
Se cierra ya que se asigna la tarea de implementación en versión móvil en el Issue #210
