### ISSUE TITLE
1.2.0 Login usando API Facebook

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#23]
Prototipo funcional backend del  Login usando api de Facebook

**Comment by ghost** [comment]
Login usando API de Facebook

- [x]  Tener o crear cuenta en Facebook.
- [x]  Entrar a Facebook console developers-https://developers.facebook.com/
- [x]  Crear una nueva aplicación Facebook para uso AppID y AppSecred - https://developers.facebook.com/apps/274779419622584/dashboard/
- [x]  Habilitar API y crear token para consultas
- [x] Leer la informacion y habilitar la API.

**Comment by ghost** [comment]
El código y la documentado fue cargado en el repositorio.
Saludos.

**Comment by ghost** [comment]
Se trabaja la modificación en el issues #149, e según el feedback debe ser en php si no en JavaScript por lo que se trabaja con el  nuevo marco de trabajo.
