### ISSUE TITLE
4. Modulo Administración del Juego

### ISSUE THREAD

**Issue by zergiozerna81** [ISWPOLI/Pacto-de-Honor#283]
Actividades a realizar Sprint 7:

- [x] Escribir historias de usuario.

- [x] Definir la funcionalidad para la generación de reportes.

- [x] Modelo de arquitectura a utilizar en el diseño del modulo administración.

- [x] Crear en el repositorio carpeta de proyecto web Administración.

- [x] Consolidar mockups de modulo administración.

- [x] Realizar mockups de reportes.

**Comment by rzambrano112** [comment]
Se anexa version temporal de historias de usuario.
[Historias de usuario.docx](https://github.com/ISWPOLI/Pacto-de-Honor/files/880724/Historias.de.usuario.docx)

**Comment by rzambrano112** [comment]
Teniendo en cuenta los css de cada diseño del modulo de administración junto con los css del equipo que esta programando los diseños de los personajes es importante revisar el issue #167  para sincronizar diseños.

**Comment by rzambrano112** [comment]
Se da cumplimiento a los items del issues #283 del modulo adminiistración del juego
