### ISSUE TITLE
7.2.1 Login Redes Sociales

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#474]
**Descripción**
Login Redes Sociales.

**Tareas a realizar**
- [x] Realizar descripción de tareas a realizar. @Basespoli 

- [ ] **Incrustar en los botones previamente diseñados, los métodos para la validación de datos desde la captura de datos en los servlet. @Basespoli**  

- [x] 1. Botón para la red Social Facebook.
- [ ] 2. Botón para la red Social Microsoft.

- [ ] **Crear una red social exclusiva para el juego para poder crear una aplicación de cada una de las redes. @Basespoli**  

 - [x] 1. Crear una red social exclusiva para el juego para poder crear una aplicación de Facebook. @Basespoli  
- [ ] 2. Crear una red social exclusiva para el juego para poder crear una aplicación de Microsoft. @Basespoli 

- [ ] **Crear la aplicación dentro de cada red social a utilizar. @Basespoli**  

- [x] 1. Crear la aplicación dentro de la red social facebook.
- [ ] 2. Crear la aplicación dentro de la red social Microsoft.

**_Descargar el SDK de cada aplicación y almacenarlo de modo de poder tener la versión más reciente de los desarrolladores de cada Api de la red social._**

- [ ] Conectar el proyecto mediante la arquitectura actual con cada aplicación de la red social para poder hacer consultas a los Api JavaScript. @Basespoli  

- [x] 1. Conectar y descargar la versión más actual de los SDK mediante JavaScript por la arquitectura para la red social Facebook.
- [ ] 2. Conectar y descargar la versión más actual de los SDK mediante JavaScript por la arquitectura para la red social Microsoft.

- [ ] **Implementar los métodos y pruebas de consultas a los Api por medio del proyecto a la aplicación y de estos mediante el SDK a los APi.  @Basespoli** 

_**Nota: tener en cuenta que cada API proporciona sus permisos especiales, para estos se pide autorización a los desarrolladores por temas de permisos sensibles a usuarios, nos proporciona unos de consulta a los APIS básicos, 'email, public_profile, user_friends' @Basespoli .**_

- [x] 1.  Crear los métodos de consultas a los api, con las consultas de los permisos básicos que nos proporcionan y su respectivo almacenamiento para la red Social Facebook.
- [ ] 2.  Crear los métodos de consultas a los api, con las consultas de los permisos básicos que nos proporcionan y su respectivo almacenamiento para la red Social Microsoft.

- [ ] **Soportar con pruebas el login y el cierre de  sesión cada red social de cada red social.**

- [x] 1. Soportar con pruebas el login y el cierre para red social Facebook.
- [ ] 2. Soportar con pruebas el login y el cierre para red social Microsoft.

_**Nota: Facebook: se almacena un token alfanuméricos por la aplicación  para tener el acceso de mi aplicación al Api.  @Basespoli**_

**Comment by ghost** [comment]
Se realizan las tareas que se consideran pertinentes según lo conversado con los Scrum Master para la  la autentificación con redes sociales de login con la aplicación.

tiempo empleado 15 min

**Comment by ghost** [comment]
Se hace la verificación de la cuenta de email creada polifighters@gmail.com y esta tiene verificación de dos pasos con celular de la persona que lo creo, por lo que se habla con el creador para poder desbloquearla. 

Tiempo empleado 30 min

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/25758763/25606844/38a8c5cc-2ed9-11e7-95aa-64b9a5ba9b72.png)

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/25758763/25606932/aea2cd5e-2ed9-11e7-8da8-7a05a3f3c797.png)

**Comment by ghost** [comment]
Se crea la cuenta de facebook con la cuenta de correo creada con este propósito, ya se logro desbloquear la cuenta para poder hacer la confirmación de creación de la red social facebook. 


![image](https://cloud.githubusercontent.com/assets/25758763/25647053/411ef96e-2f84-11e7-8c3e-a198b59fa6c9.png)


![image](https://cloud.githubusercontent.com/assets/25758763/25647091/8f8437d6-2f84-11e7-9522-e4b995601f41.png)


Tiempo empleado 1 hora

**Comment by ghost** [comment]
Se continua con la autenticación desde redes sociales, a continuación se presenta todo el proceso para la creación de un login desde la red social Facebook, donde se crea un id asociado, una clave secreta, una versión del API para su posterior uso en nuestro proyecto.

1.  Crear la cuenta de la red social para poder tener acceso la integración de los desarrolladores de la misma red social.

![image](https://cloud.githubusercontent.com/assets/25758763/25688930/e1577644-3048-11e7-9899-fcfc5559aef8.png)


2. ingresar a https://developers.facebook.com/docs/graph-api, crear cuenta de desarrollador para activar los permisos de la aplicación obtener el Id de aplicación y poder tener el Token para hacer las consultas al API-Graph para poder hacer la obtención de datos.

![image](https://cloud.githubusercontent.com/assets/25758763/25688939/f82d2a94-3048-11e7-8a18-5e44c670e046.png)



3. Después de autentificar la cuenta de red social asociada mediante el número telefónico, en este caso se usó el personal ya que es indispensable para la activación; Creó la aplicación  

![image](https://cloud.githubusercontent.com/assets/25758763/25688946/0150196a-3049-11e7-8c15-b82803af1a8f.png)


Luego de crear el identificador de la aplicación puedo crear el producto o aplicación para poder obtener el token.

![image](https://cloud.githubusercontent.com/assets/25758763/25688948/09dae39e-3049-11e7-9a0f-4cb215f9dd12.png)

  
Inicial se crea un producto para Web según la arquitectura que se está trabajando, se contempla que el módulo de administración y la autenticación junto con el portal se está trabajando  web. 

![image](https://cloud.githubusercontent.com/assets/25758763/25688954/155953a4-3049-11e7-83a7-bf3175170cd8.png)


Guia desde la página de los desarrolladores para añadir sitios web o sitios para móviles, para contemplar que se despliegue en web y móviles vía web.

![image](https://cloud.githubusercontent.com/assets/25758763/25688959/21495e66-3049-11e7-9b68-8a0b9f7a1c89.png)

Se determina por la estructura del juego, se requiere de un SDK con JAvaScript.

![image](https://cloud.githubusercontent.com/assets/25758763/25688972/31cb5532-3049-11e7-8daa-e7f0d6a237b7.png)

Donde  ya contamos con un identificador de aplicación de Facebook y contamos con el sitio para alojar los archivos HTML.

![image](https://cloud.githubusercontent.com/assets/25758763/25688982/404f4fbe-3049-11e7-98c6-c0d6450e20f4.png)

Sitio : `http://pactodehonor.co.nf/`
Después de comprobar los requerimientos básicos podemos continuar con la creación del producto.

![image](https://cloud.githubusercontent.com/assets/25758763/25688997/5ec44df0-3049-11e7-8a8b-f2fc14a281e1.png)

Como  ya podemos verificar ya contamos con un Id de aplicación, una versión de la API. y una clave secreta ya solo nos resta configurar la aplicación para poder traer el SDK y indicarle el sitio o dominio donde queremos que se aloje la información de HTMl que se requiere para el funcionamiento.

elegimos la plataforma para el uso del SDK  y poder descargar el SDK correcto.

![image](https://cloud.githubusercontent.com/assets/25758763/25689010/712da68a-3049-11e7-9a88-ba09963d5cdd.png)

De la cual según la estructura vamos a seleccionar sitio Web.

![image](https://cloud.githubusercontent.com/assets/25758763/25689019/90938a08-3049-11e7-97b9-af03c25a5052.png)

La cual nos da un inicio rápido para la configuración del producto y para la configuración del SDK con JavaScript.
![image](https://cloud.githubusercontent.com/assets/25758763/25689027/9f182a2a-3049-11e7-99a8-7b2d4ed48287.png)

**Comment by ghost** [comment]
`<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '713189185529900',
      xfbml      : true,
      version    : 'v2.9'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
`

**Comment by ghost** [comment]
Tenemos el Script del SDK  y su configuración,  si se requiere de configuraciones adicionales tenemos el en la parte final  la opción. Nos solicita donde serán almacenados los archivos HTML.

![image](https://cloud.githubusercontent.com/assets/25758763/25691787/9c9f83aa-3063-11e7-9331-a6f345a9fef5.png)

Cuando identificamos el dominio que que se requiere para almacenar algunos archivos HTML para el funcionamiento nos despliega pruebas de integración rápidas para verificar el acoplamiento.

![image](https://cloud.githubusercontent.com/assets/25758763/25691794/adbb9214-3063-11e7-86f9-8ce2782d39bb.png)

**Comment by ghost** [comment]
**div**
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true"
/**div**

**Comment by ghost** [comment]
![image](https://cloud.githubusercontent.com/assets/25758763/25691832/f9933d22-3063-11e7-9b9d-6e582e4a7901.png)


Con esto hemos logrado crear una cuenta en una red social “Facebook” con la cual asociamos una cuenta de desarrollador, la cual nos da un Id de aplicación mencionado anteriormente y una clave secreta con un APi asociado, configuramos el dominio indicado para poder almacenar algunos documentos HTML para el funcionamiento del SDK, del cual vamos a usar sus librerías y poder implementar consultas al API desde nuestro proyecto poder realizar funciones básicas como loguearse adicionar un boton, cerrar sesion, etc.

Tiempo Empleado 2 horas

**Comment by ghost** [comment]
Se descarga la versión del SDK Final y se está acoplando al proyecto en Netbeans para hacer uso de sus librerías  y acoplar el desarrollo con la aplicación de la red social. 

Tiempo empleado 1 hora.

**Comment by ghost** [comment]
Se realiza  pruebas del SDK pero no es posible tener la versión actual con composer, se este determinando como se puede tener la versión actual para que sea descargada de internet en line hy asociada al proyecto.

tiempo empleado 1 hora

**Comment by ghost** [comment]
- [x] 1. Botón para la red Social Facebook.


`<input href="#" id="facebook"  type="submit" value="Facebook"/>`

**Comment by ghost** [comment]
- [x]  1. Conectar y descargar la versión más actual de los SDK mediante JavaScript por la arquitectura para la red social Facebook.

`<script> (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  </script>`


` window.fbAsyncInit = function () {
        FB.init({
            appId: app_id,
            status: true,
            cookie: true,
            xfbml: true,
            version: 'v2.9'
        });`

**Comment by ghost** [comment]
- [x]  1. Soportar con pruebas el login y el cierre para red social Facebook.

![image](https://cloud.githubusercontent.com/assets/25758763/25927741/ab7cd904-35bd-11e7-8339-0c042d25b66d.png)

**Comment by ghost** [comment]
Se sube diagrama de flujo de autenticación con facebook solicitado.

![image](https://cloud.githubusercontent.com/assets/25758763/26005292/3e8aaf3c-36fe-11e7-9ad0-a8e91745b9ba.png)


Tiempo de la tarea 40 min.

**Comment by jrsosago** [comment]
@Basespoli Tarea nueva a realizar:

- [ ] Asignar tareas pertenecientes a esta Issue para @CristianGarzonBernal Sprint 14

**Comment by CamilaG08** [comment]
Se cierra este Issue debido a nuevas asignaciones @DiegOliveros
