### ISSUE TITLE
1.1.41 Mejorar todo el juego

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#523]
Mejorar todo el juego.
**Tareas a realizar**
- [ ] Revisar y arreglar la funcionalidad de todos los módulos del juego.

- [x] encapsular las cajas sorpresa

- [x] encapsular el modulo de compra

- [x] encapsular el modulo de creditos

- [x] encapsular el modulo de logros

- [x] encapsular  boot

- [x] encapsular seleccion Personajes

- [x] perfil Jugador

- [x] Arreglar errores de los escudos 

- [x] Arreglar los errores de los saltos en el campo de batalla

- [x] Mejorar la visualización de los ataques en el campo de batalla

- [x] Mostrar el nivel de los personajes de un jugador

**Comment by CamilaG08** [comment]
En caso de ser necesarios sprites o cambios adicionales que tengan que ver con otra dependencia, realizar un documento con los requerimientos necesarios.

**Comment by CamilaG08** [comment]
Debido a la complejidad de la tarea, se mueve al Sprint 14

**Comment by CamilaG08** [comment]
Fecha máxima de entrega: Lunes 15 de Mayo

**Comment by nmartinezmarin** [comment]
https://github.com/ISWPOLI/Pacto-de-Honor/pull/610
https://github.com/ISWPOLI/Pacto-de-Honor/pull/615
Se realiza el encapsulamiento de:
boot
seleccion Personajes
Perfil Jugador
Se corrigen los errores en salto
se modifica el código para que funcione cuando los personajes se
intercambien posiciones
se cambias las teclas con las que se realizan los ataques y el escudo
de plagio(N,M)
SeleccionPersonaje
Se agregan los niveles de cada personaje


Tiempo de trabajo :11 horas

**Comment by nmartinezmarin** [comment]
No se finaliza por la reasignacion de tareas

**Comment by nmartinezmarin** [comment]
Se realiza el merge de las corecciones del salto para la version movil 
https://github.com/ISWPOLI/Pacto-de-Honor/pull/666
