### ISSUE TITLE
1. Escenarios y navegación

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#54]
**Descripción**

Todo lo referente a la creación, manejo, visualización de los escenarios y navegación del jugador.

**TAREAS**

- [x] Mundos y escenarios
- [x] Selección del avatar
- [x] Mapa de navegación
- [x] Selección de niveles
- [x] Cambio de un nivel/mundo a otro
- [x] Sección del jugador (Perfil)

**Comment by jrsosago** [comment]
- [ ] 1.1.1  Mockups mapa primer y segundo mundo #122 
- [ ] 1.1.2 Algoritmo de batalla #128
