### ISSUE TITLE
7. Pacto de Honor : Social Networking

### ISSUE THREAD

**Issue by JuanCheroslan** [ISWPOLI/Pacto-de-Honor#670]
Esta Epica tendra relacionada toda la informacion con respecto al social networking de la aplicacion contiene las siguientes caracteriscticas

- [x] Investigacion de modelos de Chat

- [x]  Investigacion de modelos de Mensajeria

- [x] Modelado de Base de Datos

- [ ] Creacion de Servicios Agregar Amigos

- [ ] Creacion de Servicios Chat

- [x] Creacion de Servicios Mensajeria

**Comment by jnrubiano** [comment]
- Se creó una tabla llamada "mensaje" el cual contiene un campo llamado "isChat" el cuál permitirá determinar si el mensaje es de char o no. El tipo del campo es boolean,
- Se creó el servicio "Mensaje" que contiene los métodos descritos en el issue #675
