### ISSUE TITLE
6. Administración

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#77]
En está epica se encuentran los siguientes reportes:
- [x] Product Owner. Issue #47 
- [x] SRUM Master. Issue #42

**Comment by zergiozerna81** [comment]
Actividades a realizar Sprint 7:

- [ ] Escribir historias de usuario

- [ ] Crear en el repositorio carpeta de proyecto web Administración.

- [ ] Consolidar mockups de modulo administración.

- [ ] Realizar mockups de reportes.

- [ ] Definir la funcionalidad para la generación de reportes

**Comment by DiegOliveros** [comment]
@CamilaG08  @jrsosago @jolarter @JuanCheroslan @wpradere Esto es preocupante faltando 6 horas para que cierre el sprint ![image](https://cloud.githubusercontent.com/assets/2998313/24570965/0facde6e-1634-11e7-9266-22be4d34362c.png)

**Comment by jrsosago** [comment]
Se cierra está Épica, debido a que se acaba el semestre, el objetivo de está Épica era hacer los diferentes reportes de SCRUM Master y los reportes de Product Owner, se cumple está tarea a cabalidad.
