### ISSUE TITLE
5. Documentación

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Pacto-de-Honor#83]
**Tarea a realizar**

- [x] Recopilar y realizar documentación de todos los aportes subidos a github.
- [x] Pasar las historias de usuario al formato IEEE 830 de requerimientos.
- [x] Repositorio de los mockups definitivos para los escenarios, mapa de navegación y personajes.
- [ ] Recopilación y estandarización de los diferentes documentos presentados en los Issues.
- [x] Documentación del código que se presenta para el desarrollo del juego.

**Comment by jrsosago** [comment]
No se subió reporte del trabajo hecho desde el miércoles hasta hoy 25 de febrero.

**Comment by rzambrano112** [comment]
Buenas Tardes
El motivo del mensaje es para notificar que la actividad asignada para esta semana del 22 al 25 de febrero era realizar  la creación y modificación de los logros y también los ajustes respectivos a los mismos debido a que se tuvo que realizar  diferentes cambios.
La tarea asignada  tal cual se prescribe en la los reportes Scrum Master era la siguiente :

![image](https://cloud.githubusercontent.com/assets/20976993/23334051/0a3e253a-fb65-11e6-9115-599473ee30f4.png)

Esta actividad fue realizada a cabalidad durante la semana mencionada es decir hasta el 22 de febrero realizando un avance significativo para dicho día. Sin embargo, la tarea asignada el 25 de febrero  era realizar las modificaciones de los logros propuestos dado que se hicieron a los mismos por petición de los compañeros del modulo de combate y del de poderes. Razón  por la cual la tarea asignada para el 25 de febrero  respecto a las modificaciones a dicha actividad   como segunda actividad se entrego el día 24   de febrero, completando la entrega de los item solicitados.
![image](https://cloud.githubusercontent.com/assets/20976993/23334081/7ccca946-fb65-11e6-92dc-d95a38e82c47.png).

Ahora bien de manera respetuosa recibi el siguiente mensaje :
![image](https://cloud.githubusercontent.com/assets/20976993/23334093/de3fc3b6-fb65-11e6-94f0-7a8362943ac4.png)

En donde se expresa que no he realizado trabajo durante los dias 22 al 25 de febrero cuando dicha actividad  no me correspondia tal cual se especifica en Reportes SCRUM MASTER

![image](https://cloud.githubusercontent.com/assets/20976993/23334108/26b1de86-fb66-11e6-989b-c48f8a736cb0.png).

Razón por la cual de forma respetuosa envió este mensaje aclaratorio dado que las actividades asignadas las he cumplido a cabalidad.

**Comment by jrsosago** [comment]
Se cierra está Issue, debido a que se termino el semestre con el siguiente faltante:
 
- Estandarización de todos los documentos que se encuentran en la rama principal, ya que cada uno tiene un formato diferente.

Se deja todo lo realizado documentado, queda faltando actualizar esta documentación, con lo que se ha seguido desarrollando.
